### ISSUE TITLE
Request to Bhavik Sir.

### ISSUE THREAD

**Issue by hasanreham05** [Bhaviktutorials/shark#1]
Pleasee make it available for Kali Linux...Please

**Comment by Bhaviktutorials** [comment]
In next update it will available for Kali Linux  and other linux distribution

**Comment by hasanreham05** [comment]
How much time will it take? 
I can’t just wait to try this tool out..

**Comment by Bhaviktutorials** [comment]
The tool is ready for kali linux 
You can check out repo..

**Comment by AdityaAmex** [comment]
shame of you your are copied the advphishing tool.

**Comment by Ignitetch** [comment]
Same of you are copied our Advphishing tool

**Comment by E343IO** [comment]
> Same of you are copied our Advphishing tool

Now U can't say that we have copied ur 's ADV
its batter then urs
