### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by streetwaveRcd** [Bhaviktutorials/shark#101]
Stuck in new update dialogue
Although I hade update 
![Screenshot_20221015-122602_Termux](https://user-images.githubusercontent.com/36700731/195977173-0d22e2df-245b-4ad4-b13f-193f8efd7134.jpg)
update

**Comment by E343IO** [comment]
> Stuck in new update dialogue Although I hade update ![Screenshot_20221015-122602_Termux](https://user-images.githubusercontent.com/36700731/195977173-0d22e2df-245b-4ad4-b13f-193f8efd7134.jpg) update

use command in readme

**Comment by streetwaveRcd** [comment]
Still same issu
