### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by streetwaveRcd** [Bhaviktutorials/shark#102]
![Screenshot_20221015-122602_Termux](https://user-images.githubusercontent.com/36700731/195992134-b004f3cb-f596-4f91-9f75-d0e84bf419fb.jpg)
Still stuck in update screen

**Comment by George152-max** [comment]
Same issue man

**Comment by George152-max** [comment]
![Uploading Screenshot_20221015-125740.png…]()

**Comment by George152-max** [comment]
![Screenshot_20221015-125740](https://user-images.githubusercontent.com/78982842/195992790-73cc4186-c09d-47e6-917a-e8d16aa76b81.png)
Crazy shit

**Comment by George152-max** [comment]
If I run the same commands on termux, it will direct me to here, nothing is working

**Comment by streetwaveRcd** [comment]
U think they forgot to change the version 😅🤣

**Comment by George152-max** [comment]
If I run the same commands on termux, it will direct me to here, nothing is working

**Comment by George152-max** [comment]
Man I even tried reinstalling shark, same issue

**Comment by streetwaveRcd** [comment]
I re install termux even same

**Comment by George152-max** [comment]
Jeez someone do something about this

**Comment by George152-max** [comment]
I need to work

**Comment by E343IO** [comment]
##### Ho god sorry guys them problem came becoz of Beta branch of mine repo it has been fixed,
Once again sorry

**Comment by George152-max** [comment]
It hasn't been fixed, still showing me the same thing

**Comment by streetwaveRcd** [comment]
Still unfixed

**Comment by streetwaveRcd** [comment]
> line 181
function check_update() {
        connection
        version=$(curl -L -s https://raw.githubusercontent.com/tech2gamer/shark/Beta/shark | grep -w "VERSION=" | head -n1)
	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
        if [ ${latest_version} = ${VERSION} ];then
                echo -e "\tReading \tpackage \tlists... \tDone
                         \tBuilding \tdependency \ttree
                         \tReading \tstate \tinformation... \tDone
                         \tshark \tis \talready \tthe \tnewest \tversion \t($VERSION)." | awk '{$1=$1};1'
	        exit 1
	else
		main_update
		exit 1

**Comment by streetwaveRcd** [comment]
![Screenshot_20221016-063355_Chrome](https://user-images.githubusercontent.com/36700731/196015143-bb3c1164-d455-4be4-8049-c472926a66e5.jpg)
Version is 2.5
1

**Comment by streetwaveRcd** [comment]
![Uploading Screenshot_20221016-063613_Chrome.jpg…]()

**Comment by streetwaveRcd** [comment]
![Screenshot_20221016-063613_Chrome](https://user-images.githubusercontent.com/36700731/196015224-db3afe70-981b-4e68-b2fd-ae0e9e01e922.jpg)

Your version

**Comment by streetwaveRcd** [comment]
Check this to screenshot maybe it helps fixing the issue

**Comment by E343IO** [comment]
**Man just re-install tool**

**Comment by E343IO** [comment]
> It hasn't been fixed, still showing me the same thing

**Bro🤣 u have to reinstall the tool**
