### ISSUE TITLE
Fails to update

### ISSUE THREAD

**Issue by Brokong** [Bhaviktutorials/shark#106]
Anyone else having issues with this?

**Comment by E343IO** [comment]
> Anyone else having issues with this?

**This has been already patched, You have to re-install tool once again.**
-Or-
**Follow the steps below:
Just copy and paste the command**
```bash
wget https://github.com/Bhaviktutorials/shark/raw/master/shark -O $PREFIX/shark;chmod +x $PREFIX/shark; mv $PREFIX/shark $PREFIX/bin
```
