### ISSUE TITLE
Not Found The requested resource / was not found on this server.(Error I am facing)

### ISSUE THREAD

**Issue by hasanreham05** [Bhaviktutorials/shark#17]
Bhavik  buddy I am getting the link but when i open the link it shows:
Not Found
The requested resource / was not found on this server.
--------------------------------------------------------------
PLEASE HELP ME

**Comment by Bhaviktutorials** [comment]
Please Provide me Screen Shots

**Comment by hasanreham05** [comment]
sir i dont know how to upload pic on this... can i send it on insta?

**Comment by Bhaviktutorials** [comment]
Here is a option of attach files click on it and select the screenshot

**Comment by hasanreham05** [comment]
[](url) https://share.icloud.com/photos/0rtADewByr7GVBP_DgLz0VliA

**Comment by Bhaviktutorials** [comment]
bro first of all issue has been occur during installtion some files hasnt been saved in your tool 
PC me on WhatsApp  +917977821437

**Comment by hasanreham05** [comment]
Bro u blocked my no long back 😞😞

**Comment by hasanreham05** [comment]
Bhavik bro u blocked my WhatsApp number long back 
 My Number:9550418290

**Comment by Bhaviktutorials** [comment]
bro i said to whatsapp on that on no
i will solve your issue

**Comment by hasanreham05** [comment]
Sir gave his precious time and solved the issue
