### ISSUE TITLE
No file on directories

### ISSUE THREAD

**Issue by bittusrv** [Bhaviktutorials/shark#18]
Please upgrade commands

**Comment by Bhaviktutorials** [comment]
Sir please provide some screenshots so we can rectifie the issue

**Comment by Suhas4321** [comment]
Ok should I send it here or in whatsapp

**Comment by Bhaviktutorials** [comment]
Here

**Comment by Suhas4321** [comment]
I have video I have sent it in whatsapp bro 😬😬... Link isn't working just
