### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by xAvatar6969** [Bhaviktutorials/shark#19]
I have completed the installation, but when I type `shark` it gives error. ![Screenshot_20201026-175015.jpg](https://user-images.githubusercontent.com/64364834/97202394-d41a2480-17b3-11eb-82cb-5d56a8cc3fbd.jpg)

**Comment by 8757195139** [comment]
Doesn't work

**Comment by Bhaviktutorials** [comment]
It meana you have not install properly
