### ISSUE TITLE
Tool not started with ngrok sar

### ISSUE THREAD

**Issue by legendx22** [Bhaviktutorials/shark#24]

**Comment by legendx22** [comment]
But bro Mene ngrok already install krrakha h isliye Mene /setup ka use ni kiya 🤐🤐

**Comment by legendx22** [comment]
Seedha tool start krdiya 😶

**Comment by Bhaviktutorials** [comment]
We Can saw people directly to install Ngrok Right?
Though we have included ngrok in Tool (Script) Because we have installed the ngrok into a specific folder to run it faster!!
So just run the setup again let Ngrok Install and don't take it will work fine and you just have to put ngrok token.

**Comment by legendx22** [comment]
Oook sar
