### ISSUE TITLE
Cannot create directory: P

### ISSUE THREAD

**Issue by shittyfollower** [Bhaviktutorials/shark#25]
Keep getting this error:
cp: cannot create directory '/usr/bin/phs': Permission denied
cp: cannot create regular file '/usr/bin/shark': Permission denied

**Comment by Bhaviktutorials** [comment]
did you give chmod permission before running the setup file?

**Comment by E343IO** [comment]
> Keep getting this error: cp: cannot create directory '/usr/bin/phs': Permission denied cp: cannot create regular file '/usr/bin/shark': Permission denied

use sudo bash setup
