### ISSUE TITLE
Installing stuck.

### ISSUE THREAD

**Issue by Jazzbil** [Bhaviktutorials/shark#27]
Hello 
When I try to bash . /setup  im stuck on ngrok step 

[~] Instaling ngrok ..

[~] Successfuly installed

[~] Inflating ngrok

And nothing happened .  Just stuck in there

I'm using termux non rooted device 

I have already installed  ngrok and using ath key in it

**Comment by Bhaviktutorials** [comment]
> Hello
> When I try to bash . /setup im stuck on ngrok step
> 
> [~] Instaling ngrok ..
> 
> [~] Successfuly installed
> 
> [~] Inflating ngrok
> 
> And nothing happened . Just stuck in there
> 
> I'm using termux non rooted device
> 
> I have already installed ngrok and using ath key in it

>>>> stiil facing same issue??

>>>> run :
 
>>>>bash -x setup 

>>>>provide me screenshot of it.

**Comment by Jazzbil** [comment]
It's solved  thank you for helping

**Comment by Rob2234** [comment]
Same error how can i fix this??

**Comment by Bhaviktutorials** [comment]
> Same error how can i fix this??

and you provide a screenshot?

**Comment by Bhaviktutorials** [comment]
Comment it on #27 
"Dear users,

Shark is already enhanced for its installation please check your environment, is up-to-date?
If not check our readme Android section.
                                 Thanking You 
                           @Bhaviktutorials
