### ISSUE TITLE
Not working in Kali

### ISSUE THREAD

**Issue by hasanreham05** [Bhaviktutorials/shark#3]
The tool has installed and it shows the following options:

root@kali:~/shark# ls

kali-setup  LICENSE  phs        setup  shark_logo

kali-shark  log.txt  README.md  shark

What do I do ? 
Please also put commands for Linux as you put for Termux..

**Comment by Bhaviktutorials** [comment]
run ./kali-setup 
and when it is done setting up shark simply run shark from any directory
