### ISSUE TITLE
Masking link error.

### ISSUE THREAD

**Issue by BangCash** [Bhaviktutorials/shark#30]
Greetings, facebook is splitting the masking link after the @, that's why it gives an error. Example: tuexample.com@miexample.com

Compose 2 url instead of one, otherwise it's great, thanks.

**Comment by Bhaviktutorials** [comment]
okay!!!

**Comment by jaykali** [comment]
Masking URL technique is taken from my [MaskPhish](https://github.com/jaykali/maskphish) tool.
