### ISSUE TITLE
Too many connections!

### ISSUE THREAD

**Issue by hasanreham05** [Bhaviktutorials/shark#31]
![3BEA5F37-BC0B-44AE-BC94-79783BF83E85](https://user-images.githubusercontent.com/68740723/120061388-a2837780-c07a-11eb-9359-2dca41a97a2a.jpeg)

Hello Bhavik, 
Shark is just awesome.. I have never had any regret subscribing you on YouTube and watching your videos you never fail to impress me.. Also shark after the update is just killing it but there one one problem if the victim reloads the page then it shows ‘too many connections’ which is the only issue.. Hope you fix this out soon! And ya we do want a new update next month and I am creating multiple accounts on GitHub for giving stars to shark 🦈..😉

**Comment by Bhaviktutorials** [comment]
this error is because of the free version of ngrok you can use the VIP version to minimize this error

**Comment by tech2gamer** [comment]
Bruh just change ngrok that u own  private ngrok.

**Comment by tech2gamer** [comment]
Bruh just replace ngrok use ur own, paste ur Ngrok to /bin directory.
