### ISSUE TITLE
[~] Your phishing url >> https://insyagtam.com-@Error: Please specify a URL to shorten.

### ISSUE THREAD

**Issue by justinruck080** [Bhaviktutorials/shark#34]
I have ngrok all setup I tried deleting the tool and reinstalling I deleted and redid ngrok nothing work's, please fix this is the only phishing tool that I found to actually work

**Comment by Bhaviktutorials** [comment]
did you try in google cloud shell? I have given the option in the readme

**Comment by niazi99** [comment]
https://insta.com-free-followers@Error: Please specify a URL to shorten.  Link is again showing an error like this. How to solve the error.

**Comment by justinruck080** [comment]
Google shell doesn't work either
