### ISSUE TITLE
instagram attack is not working

### ISSUE THREAD

**Issue by purveshpatel511** [Bhaviktutorials/shark#37]
After giving input of mask url domain(here: https://instagram.com/) and key-words(here: valorant), tool generate the following link: `https://lnstagram.com/-valorant@` and while visiting this link, it redirect to official instagram page where 404 error has been shown by them.

would you please help me out here??

**Comment by purveshpatel511** [comment]
BTW, i am running shark version 2.0.4

**Comment by Bhaviktutorials** [comment]
please provide us ScreenShot

**Comment by purveshpatel511** [comment]
Here you go,

![Screenshot1](https://user-images.githubusercontent.com/59075054/132077369-17854d50-10e4-43fa-9896-c5ad49f7ba7f.png)
![Screenshot2](https://user-images.githubusercontent.com/59075054/132077372-ded07839-5b5e-444a-9574-89c24e3bf52b.png)
![Screenshot3](https://user-images.githubusercontent.com/59075054/132077373-f17200bf-92bf-4b47-bd0c-2826bad880f7.png)
![Screenshot4](https://user-images.githubusercontent.com/59075054/132077374-d5119a5b-3bc7-4628-8208-96fe21af533f.png)

**Comment by Bhaviktutorials** [comment]
here you have made mistakes 
![132077369-17854d50-10e4-43fa-9896-c5ad49f7ba7f](https://user-images.githubusercontent.com/64035221/132091023-e28a5dfb-cc1b-457c-a763-015d61f65321.png)
you have typed https://instagram.com/ 
Don't put / after .com it will take to the original site, we also have given examples, you can check there only we have not given / at last.
now remove / after .com and try again

**Comment by purveshpatel511** [comment]
Bro still not working......and here are screenshots that you asked for.

![Screenshot1](https://user-images.githubusercontent.com/59075054/132093751-1d733df8-5373-4f07-85e2-840d4f4ee291.png)
![Screenshot2](https://user-images.githubusercontent.com/59075054/132093753-301d717a-17d9-497b-ada6-4c3dda38cfbb.png)

BTW, the URL shown in above screenshot is not valid.

**Comment by Bhaviktutorials** [comment]
Bro this time link only is not generate fully try again
