### ISSUE TITLE
Не делает норм ссылку

### ISSUE THREAD

**Issue by Vlad892** [Bhaviktutorials/shark#49]
![Screenshot_2021-11-02-01-56-16-016_com termux](https://user-images.githubusercontent.com/62385559/139734236-26bed627-520b-41cb-b02e-c115f1b9d2f5.jpg)

Не даёт норм ссылку через локальный хост работает а ссылку норм не выдаёт

**Comment by Bhaviktutorials** [comment]
check the ngrok token if u have put it properly or not!

**Comment by tech2gamer** [comment]
> ![Screenshot_2021-11-02-01-56-16-016_com termux](https://user-images.githubusercontent.com/62385559/139734236-26bed627-520b-41cb-b02e-c115f1b9d2f5.jpg)
> 
> Не даёт норм ссылку через локальный хост работает а ссылку норм не выдаёт

Dm me on instagram:- https://instagram.com/tech2.gamer/

**Comment by tech2gamer** [comment]
Uploading Termux_2021-11-03-01-35-28_001.mp4…

**Comment by Vlad892** [comment]
> > ![Screenshot_2021-11-02-01-56-16-016_com termux](https://user-images.githubusercontent.com/62385559/139734236-26bed627-520b-41cb-b02e-c115f1b9d2f5.jpg)
> > Не даёт норм ссылку через локальный хост работает а ссылку норм не выдаёт
> 
> Пожалуйста, проверьте и настройте свой termux, прежде чем использовать инструмент [Shark](https://drive.google.com/u/4/uc?id=1pDKb5svQLjEN-Mc2A2ERKY0MdYQV6ruP&export=download.mp4) : - [Termux-setup](https://drive.google.com/u/4/uc?id=1pDKb5svQLjEN-Mc2A2ERKY0MdYQV6ruP&export=download.mp4)
> 
> Дай мне в инстаграм: - https://instagram.com/tech2.gamer/

I did everything as shown and now this is the problem 
![IMG_20211105_233320](https://user-images.githubusercontent.com/62385559/140554353-69b55f2b-920a-46b2-9808-759e733b5baf.jpg)

**Comment by tech2gamer** [comment]
> > > ![Screenshot_2021-11-02-01-56-16-016_com termux](https://user-images.githubusercontent.com/62385559/139734236-26bed627-520b-41cb-b02e-c115f1b9d2f5.jpg)
> > > Не даёт норм ссылку через локальный хост работает а ссылку норм не выдаёт
> > 
> > 
> > Пожалуйста, проверьте и настройте свой termux, прежде чем использовать инструмент [Shark](https://drive.google.com/u/4/uc?id=1pDKb5svQLjEN-Mc2A2ERKY0MdYQV6ruP&export=download.mp4) : - [Termux-setup](https://drive.google.com/u/4/uc?id=1pDKb5svQLjEN-Mc2A2ERKY0MdYQV6ruP&export=download.mp4)
> > Дай мне в инстаграм: - https://instagram.com/tech2.gamer/
> 
> I did everything as shown and now this is the problem ![IMG_20211105_233320](https://user-images.githubusercontent.com/62385559/140554353-69b55f2b-920a-46b2-9808-759e733b5baf.jpg)

Connect with me on instagram:- https://instagram.com/tech2.gamer/
