### ISSUE TITLE
It isn't working again

### ISSUE THREAD

**Issue by justinruck080** [Bhaviktutorials/shark#50]
>> https://favajajhejs.com-@Error: You haven't supplied a valid URL..!!

**Comment by tech2gamer** [comment]
> > > https://favajajhejs.com-@Error: You haven't supplied a valid URL..!!

Hey dear, dm me on instagram https://instagram.com/tech2.gamer/

**Comment by tech2gamer** [comment]
Setup your termux :- [Termux-setup](https://drive.google.com/u/4/uc?id=1pDKb5svQLjEN-Mc2A2ERKY0MdYQV6ruP&export=download.mp4)
