### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by paddy12345678** [Bhaviktutorials/shark#63]
![WhatsApp Image 2021-11-24 at 4 15 24 PM](https://user-images.githubusercontent.com/94964287/143224256-370012be-aefc-4ea9-a6a3-f9e50e9b3882.jpeg)
 sir after this i am not getting further phishing link. what to do

**Comment by paddy12345678** [comment]
waiting for your feedback

**Comment by tech2gamer** [comment]
> waiting for your feedback

Man pls go for github.com/tech2gamer/shark

**Comment by paddy12345678** [comment]
sir i didnt understand exactly what to do with reborn beta.
can u give the steps so can come out with the error of not geeting phishing link

**Comment by tech2gamer** [comment]
> sir i didnt understand exactly what to do with reborn beta. can u give the steps so can come out with the error of not geeting phishing link

Click on reborn beta then for termux command that's it.

**Comment by paddy12345678** [comment]
> > sir i didnt understand exactly what to do with reborn beta. can u give the steps so can come out with the error of not geeting phishing link
> 
> Click on reborn beta then go for termux command that's it.

sir i clicked on ur given link (reborn beta) and then run shark in termux but still problem persist. Phishing url is not generated

**Comment by tech2gamer** [comment]
> > > sir i didnt understand exactly what to do with reborn beta. can u give the steps so can come out with the error of not geeting phishing link
> > 
> > 
> > Click on reborn beta then go for termux command that's it.
> 
> sir i clicked on ur given link (reborn beta) and then run shark in termux but still problem persist. Phishing url is not generated

what's app me will fix it out... [Click here](https://wa.me/+919904239850)

**Comment by justinruck080** [comment]
You need to manually setup ngrok in the shark directory if you need help dm me @frostdeday on Instagram

**Comment by tech2gamer** [comment]
> You need to manually setup ngrok in the shark directory if you need help dm me @frostdeday on Instagram

Hey buddy now in some days will update it as zphisher is and more check [README.md](https://github.com/tech2gamer/shark/blob/Beta/README.md)

**Comment by justinruck080** [comment]
What? I'm only saying because it worked for me

**Comment by tech2gamer** [comment]
> What? I'm only saying because it worked for me

Is it working for u?

**Comment by 27DenNis27** [comment]
Hello, good, the commands do not work for me, what can I do? i'm in termux

**Comment by 27DenNis27** [comment]
Hello, good, the commands do not work for me, what can I do? i'm in termux

**Comment by E343IO** [comment]
> Hello, good, the commands do not work for me, what can I do? i'm in termux

First you have to update your termux -: [see video via clicking here.](https://drive.google.com/u/4/uc?id=1-4pX8xLXJe1qQPlNrsPxGVwStK6u3D-s&export=download.mp4)
