### ISSUE TITLE
How to delete old credentials?

### ISSUE THREAD

**Issue by mountaincastle47** [Bhaviktutorials/shark#97]
Please there are too many of them now

**Comment by E343IO** [comment]
> Please there are too many of them now

First of all sorry for this inconvenien, we've patched it in shark official v2.5.1 that stable too
And for now use command below to remove manually :
# For termux
```bash
Take backup 
cp $PREFIX/share/shark/phs/.dumplog.txt <path_to_store>
rm -rf $PREFIX/share/shark/phs/.dumplog.txt
```
# for kali 
```bash
sudo cp /usr/share/shark/phs/.dumplog.txt <path_to_store>
sudo rm -rf  /usr/share/shark/phs/.dumplog.txt
```
### Thanks for using our tool
#####  ~ Mr. Derek
